version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: example_app_backend
    ports:
      - "8003:80" # Expose port 8003 to avoid conflict
    depends_on:
      - db
    networks:
      - example_app_network
    volumes:
      - .:/var/www/html
      - vendor_example_volume:/var/www/html/vendor
    environment:
      APP_NAME: example
      APP_KEY: ${APP_KEY}
      APP_DEBUG: "true"
      APP_URL: http://localhost:8003
      ASSET_URL: http://localhost:8003
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: example
      DB_USERNAME: uexample
      DB_PASSWORD: "secure#pass"

  db:
    image: mysql:8.0
    container_name: example_app_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "secure#pass"
      MYSQL_DATABASE: example
      MYSQL_USER: uexample
      MYSQL_PASSWORD: "secure#pass"
    ports:
      - "3307:3306" # Expose MySQL on port 3307 to avoid conflict
    volumes:
      - example_dbdata:/var/lib/mysql
    networks:
      - example_app_network

volumes:
  example_dbdata:
  vendor_example_volume:

networks:
  example_app_network:
    name: example_app_network